In [1]:
import numpy as np
np.__version__

'1.24.3'

In [8]:
a = np.array([2,3,4]) #input을 받아서 numpy.ndarray를 만들어 주는 것
print(a)

print(a.dtype)

b = np.array([1.2, 3.5, 5.1])
print(b.dtype)

c = np.ndarray((3,2)) #input : shape!
print(c)

[2 3 4]
int64
float64
[[1.65766455e-316 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000]]


In [10]:
d = np.array([[1,2],[3,4]])
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
np.ones((2,3,4), dtype = np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [12]:
c = np.empty((2,3))

In [13]:
c

array([[2.10689433e-316, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

In [15]:
# range(start, stop, step)
a = np.arange(10,30,5)
print(a)

[10 15 20 25]


In [22]:
b = np.arange(0,2,0.3)
print(b)
print()
c = np.arange(0,2.1,0.3) #step 크기가 정수가 아닌 경우 stop포인트 주의하기
print(c)
print()
d = np.arange(6)
print(d)

[0.  0.3 0.6 0.9 1.2 1.5 1.8]

[0.  0.3 0.6 0.9 1.2 1.5 1.8 2.1]

[0 1 2 3 4 5]


In [20]:
#(start, stop(포함), 요소 개수
#시작하는 지점과 끝나는 지점을 등분해준다
a = np.linspace(0,2,9) #마지막 지점 포함 시킨다.!!
print(a)

[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]


In [26]:

np.set_printoptions(threshold = 50) #요소 개수 > 50
print(np.arange(10000))
print(np.arange(30))


[   0    1    2 ... 9997 9998 9999]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


In [28]:
x = np.arange(10)
print(x)
print(x[0])
print(x[1])

[0 1 2 3 4 5 6 7 8 9]
0
1


In [34]:
x = np.arange(10).reshape(2,5)
print(x)
print()
print(x[0])
print()
print(x[0,2])
print(x[1,3])

y = x[1]
print(y[3])

[[0 1 2 3 4]
 [5 6 7 8 9]]

[0 1 2 3 4]

2
8
8


In [38]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print()
print(a[[0,1,2,0],[0,2,0,1]])
# a[0,0]
# a[1,2]
# a[2,0]
# a[0,1]


[[1 2 3]
 [4 5 6]
 [7 8 9]]

[1 6 7 2]


In [41]:
#[start : stop : step]

x = np.arange(10) #0~9
print(x)
print()

print(x[2:5]) #start idx=2, stop idx = 5(포함x), step 생략 = 1

[0 1 2 3 4 5 6 7 8 9]

[2 3 4]


In [48]:
x = np.arange(100, 110) #100~109
print(x)
print()

print(x[:-7]) #start 생략 - > 처음부터 (0), stop idx = -7 (3), step 생략 = 1
print()

print(x[1:7:2])
#idx = 1, 3, 5
print()

y = np.arange(35).reshape(5,7) #0~34
print(y)
print()

print(y[1:5:2]) #axis 0 : index 1, 3
print()

print(y[1:5:2,::3]) 
#axis 0 :index 1, 3
#axis 1 :index 0, 3, 6

[100 101 102 103 104 105 106 107 108 109]

[100 101 102]

[101 103 105]

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]]

[[ 7  8  9 10 11 12 13]
 [21 22 23 24 25 26 27]]

[[ 7 10 13]
 [21 24 27]]


In [57]:
a = np.array(range(6)).reshape(2,3)
print(a)
print()

bool_idx = a>4
print(bool_idx)
print(a[bool_idx]) #true인 값만 나온다
print()

bool_idx = (a % 2 == 0)
print(bool_idx)
print(a[bool_idx])
print()

[[0 1 2]
 [3 4 5]]

[[False False False]
 [False False  True]]
[5]

[[ True False  True]
 [False  True False]]
[0 2 4]



In [66]:
a = np.arange(1, 13).reshape(3,4)
print(a)
print()

b = a[:2] #axis0 : index 0,1
# 얕은 복사!!!
print(b)
print()

b[0,0] = -1
print(b)
print(a) #a와 b가 같음(shallow copy)
print()

a = np.arange(1, 13).reshape(3,4)
b = np.copy(a[:2])
b[0,0] = -1
print(a)
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[1 2 3 4]
 [5 6 7 8]]

[[-1  2  3  4]
 [ 5  6  7  8]]
[[-1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[-1  2  3  4]
 [ 5  6  7  8]]


In [79]:
a = np.floor(10*np.random.random((3,4)))
#numpy.random.random -> 0~1 사의 숫자들로 ndarrya만들기
#입력값으로 shape을 받는다

#10이 각각의 요소에 곱해진다.
print(a)
print(a.shape)
print("-" * 30)

print(a.ravel())  #납작하게 만들었을 때 예상되는 모양을 보여줌
print()   #a 자체를 변형시키지는 않는다
print(a) 
print("-" * 30)

print(a.reshape(6,2)) #a 자체를 변형시키지는 않는다
print()
print(a)
print("-" * 30)

print(a.T)
print()
print(a)
print("-" * 30)

[[3. 5. 6. 7.]
 [1. 5. 3. 6.]
 [4. 4. 8. 5.]]
(3, 4)
------------------------------
[3. 5. 6. 7. 1. 5. 3. 6. 4. 4. 8. 5.]

[[3. 5. 6. 7.]
 [1. 5. 3. 6.]
 [4. 4. 8. 5.]]
------------------------------
[[3. 5.]
 [6. 7.]
 [1. 5.]
 [3. 6.]
 [4. 4.]
 [8. 5.]]

[[3. 5. 6. 7.]
 [1. 5. 3. 6.]
 [4. 4. 8. 5.]]
------------------------------
[[3. 1. 4.]
 [5. 5. 4.]
 [6. 3. 8.]
 [7. 6. 5.]]

[[3. 5. 6. 7.]
 [1. 5. 3. 6.]
 [4. 4. 8. 5.]]
------------------------------


In [90]:
b = np.floor(10*np.random.random((7,4)))
b.resize((2,14))
print(b)

[[1. 2. 8. 6. 0. 0. 7. 4. 9. 6. 3. 6. 8. 7.]
 [1. 1. 1. 9. 6. 1. 0. 4. 8. 2. 7. 8. 4. 9.]]


### 실습 문제 1

In [115]:
x = np.ones((5,5))
#print(x)
print()
x[1:4,1:4] = 0
print(x)
print()

x = np.zeros((5,5))
#print(x)
print()
x[1:4,1:4] = 1
print(x)


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [127]:
x = np.ones((3,3))
print(x)
print()

y = np.pad(x, pad_width = 1, mode = 'constant', constant_values = 0) 
print(y)
#input : 감쌀 어레이 , pad_width, mode = 감쌀때 뭐로 감쌀건지

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


### 실습 문제 2

In [136]:
np.set_printoptions(threshold = 100)
x = np.zeros((8,8))

#method 1
x[::2,1::2] = 1 #행작업
x[1::2,::2] = 1 
print(x)

y = np.zeros((8,8))
#method 2 - 생각해보기
con = (i % 2 == 0)


[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


### 실습 문제 3

In [147]:
x = np.array([180,72,172,66,162,60,167,53,176,80,155,60,177,77,130,40])
y = x.reshape((2,4,2))
print(y)
print()

#B, 2nd student, weight
print(y[1,1,1])

[[[180  72]
  [172  66]
  [162  60]
  [167  53]]

 [[176  80]
  [155  60]
  [177  77]
  [130  40]]]

60


# Basic operations

In [160]:
A = np.array([[1,1],
            [0,1]])
B = np.array([[2,0],
            [3,4]])

In [163]:
print(A @ B)
print()
print(A.dot(B))

[[5 4]
 [3 4]]

[[5 4]
 [3 4]]


In [168]:
B = np.arange(12).reshape(4,3)
print(B)
v = np.array([0,1,2])
C = B + v
print(C)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]
 [ 9 11 13]]


In [148]:
result = [[20180002, 'lee', 98, 80, 80,"A"],
          [20180002, 'lee', 98, 80, 110,"A"],
          [20180002, 'lee', 98 ,80, 90,"A"]]

In [149]:
print(result)

[[20180002, 'lee', 98, 80, 80, 'A'], [20180002, 'lee', 98, 80, 110, 'A'], [20180002, 'lee', 98, 80, 90, 'A']]


In [150]:
r2 = sorted(result, key = lambda x:-x[4])
print(r2)

[[20180002, 'lee', 98, 80, 110, 'A'], [20180002, 'lee', 98, 80, 90, 'A'], [20180002, 'lee', 98, 80, 80, 'A']]


In [151]:
result.sort(key = lambda x:-x[4])
print(result)

[[20180002, 'lee', 98, 80, 110, 'A'], [20180002, 'lee', 98, 80, 90, 'A'], [20180002, 'lee', 98, 80, 80, 'A']]


In [158]:
line = result[0]
print(type(line))
line = map(str, line)
print("\t".join(line))

<class 'list'>
20180002	lee	98	80	110	A
